baseURL = 'https://cs.utexas.edu/~ntaylor/'
languageCode = 'en-ca'
title = 'Nathan Taylor'
theme = 'researcher'

[markup]
  [markup.highlight]
    guessSyntax = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = 'solarized-light'
    tabWidth = 4

[params]
    author = "Nathan Taylor"
    description = "academic webzone"
    favicon = "favicon.ico"  # path to a .ico to use as favicon
    logo = ""  # url or path to a logo to put in the header

    custom_css = [""]

[params.style]  # appearance options (can be omitted)
    fontFamily = ["Carlito", "Helvetica", "Arial", "sans-serif"]
    fontSize = "12pt"
    pageWidth = "1000px"
    avatarSize = "250px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
    colorGreen = "#009900"

[menu]
    [[menu.main]]
    #name = "About"
    #url = "/about"
    #weight = 1
    [[menu.main]]
    name = "News"
    url = "/blog"
    weight = 2
    [[menu.main]]
    name = "Research"
    url = "/papers"
    weight = 3
    [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 4
    [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 5

[markup.goldmark.renderer]
    unsafe = true  # allow raw HTML in markdown files
